name: Release
on:
  release:
    types: [released]
jobs:
  buildDockerImage:
    strategy:
      matrix:
        docker: ['scratch','ubi']
    name: Build docker image ${{ matrix.docker }}
    runs-on: ubuntu-latest
    steps:
    - name: Release if tagged
      if: "!startswith(github.ref, 'refs/tags/v')"
      run: exit 78
    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_UBI_READONLY_USERNAME }}
        password: ${{ secrets.QUAY_UBI_READONLY_PASSWORD }}
    - name: build
      uses: sysdiglabs/exporter-builder@v1.2
      with:
        exporter: elasticsearch-exporter
        artifactory_token: ${{ secrets.GAR_DEV_RW_JSON_KEY }}
        artifactory_username: _json_key
        sysdig_secure_token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        tag_name: ${{ github.event.release.tag_name }}
        target: ${{ matrix.docker }}
        repository: us-docker.pkg.dev
